---
- name: Checking workspace
  assert:
    that:
      - workspace is defined
      - (workspace | length) > 0
      - workspace != 'default'
    msg: >-
      Variable 'workspace' must be defined, non-empty and not equal to 'default'

- name: Checking terraform action
  assert:
    that:
      - tf_action is defined
      - tf_action in ['apply', 'destroy']
    msg: >-
      'tf_action' must be defined and one of ['apply', 'destroy']

- name: APPLY - Directories
  delegate_to: localhost
  become: no
  run_once: yes
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ workspace_group_vars_dir }}"
    - "{{ workspace_secrets_dir }}"
    - "{{ workspace_terraform_dir }}"
  when: tf_action == 'apply'
