---
- name: Check directories exist
  file:
    path: "{{ _current_expected_dir }}"
    owner: consul
    group: consul
    state: directory
    mode: 0700
  loop: "{{ __hs_consul_expected_directories }}"
  loop_control:
    loop_var: _current_expected_dir
  tags:
    - configure

- name: Common private ssl directory
  file:
    path: "{{ __hs_consul_tls_dir }}"
    owner: root
    group: "{{ __hs_consul_ssl_cert_group }}"
    state: directory
    mode: 0750
  tags:
    - configure

- name: Add consul user to ssl-cert group
  user:
    name: consul
    groups: "{{ __hs_consul_ssl_cert_group }}"
    append: true
  tags:
    - configure

- name: Upload Vault Root CA
  copy:
    dest: "{{ __hs_consul_vault_root_ca_certificate }}"
    content: |-
      {{ hs_consul_connect_root_pki_certificate_b64 | b64decode }}
    mode: 0644
    owner: root
    group: "{{ __hs_consul_ssl_cert_group }}"
  notify: Update ca trust
  tags:
    - configure

- name: Upload CA certificate
  copy:
    src: "{{ hs_consul_local_ca_cert }}"
    dest: "{{ __hs_consul_ca_certificate }}"
    owner: root
    group: "{{ __hs_consul_ssl_cert_group }}"
    mode: 0644
  notify: Update ca trust
  when: hs_consul_use_custom_ca
  tags:
    - configure

- name: Flush handlers
  meta: flush_handlers
  tags:
    - configure

- name: Upload self certificate
  copy:
    src: "{{ _current_cert_part }}"
    dest: "{{ __hs_consul_tls_dir }}/{{ _current_cert_part.split('/')[-1] }}"
    owner: root
    group: "{{ __hs_consul_ssl_cert_group }}"
    mode: 0640
  loop:
    - "{{ hs_consul_node_cert }}"
    - "{{ hs_consul_node_cert_private_key }}"
    - "{{ hs_consul_node_cert_fullchain }}"
  loop_control:
    loop_var: _current_cert_part
  notify: Restart consul
  when: __hs_consul_is_master
  tags:
    - configure

- name: Generate encrypt key
  copy:
    dest: "{{ __hs_consul_encrypt_key_local_path }}"
    mode: 0600
    content: >
      {{
        lookup('password', __hs_consul_encrypt_key_local_path +'.gen length=32 chars=ascii_letters,digits,punctuation')
        | b64encode
      }}
  run_once: true
  become: false
  delegate_to: localhost
  no_log: true
  tags:
    - configure

- name: Write consul server configuration
  template:
    src: "consul.hcl.j2"
    dest: "{{ __hs_consul_conf_file }}"
    owner: consul
    group: consul
    mode: 0640
  notify: Restart consul
  tags:
    - configure

- name: Flush
  meta: flush_handlers
  tags:
    - configure
