---
- name: Pin consul release
  template:
    src: "apt.preferences.j2"
    dest: /etc/apt/preferences.d/consul
    mode: 0640

- name: Install common packages
  apt:
    name: "{{ packages_list }}"
    state: present
