---
- name: Prepare
  include_tasks: _prepare.yml
  tags:
    - prepare
    - online

- name: Install
  include_tasks: _install.yml
  tags:
    - install

- name: Configure
  include_tasks: _configure.yml
  when: inventory_hostname in groups['hashistack_masters']
  tags:
    - configure
