---
- name: Create local facts directory
  file:
    path: /etc/ansible/facts.d
    recurse: true
    state: directory

- name: Load os-specific vars
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __consul_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars
  tags: always

- name: Execute os-specific tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __consul_tasks_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  tags: always

- name: Make sure consul service is running
  systemd:
    name: consul
    daemon_reload: true
    state: started
    enabled: true
  when: inventory_hostname in groups['hashistack_masters']

- name: Flush
  meta: flush_handlers

- name: Wait for consul api
  wait_for:
    host: "127.0.0.1"
    port: "{{ hs_consul_api_port }}"
    timeout: 60
  when: inventory_hostname in groups['hashistack_masters']

- name: Bootstrap acl
  include_tasks: _acl_bootstrap.yml
  when:
    - inventory_hostname in groups['hashistack_masters']
    - inventory_hostname == groups[consul_inventory_masters_group][0]
    - >-
      ansible_local.consul is not defined
      or ansible_local.consul.applied is not defined
      or not ansible_local.consul.applied

- name: Install role marker
  copy:
    dest: /etc/ansible/facts.d/consul.fact
    content: >-
      {{ {'applied': True} | to_json }}
    mode: 0600

- name: Configure Vault instance using terraform
  include_tasks: _tf_configure.yml

- name: Configure consul on Masters
  include_tasks: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/_consul_masters.yml"
  when: inventory_hostname in groups['hashistack_masters']
  tags:
    - consul_masters

- name: Load group vars
  include_vars:
    dir: "{{ hs_workspace_group_vars_dir }}"
    ignore_unknown_extensions: true

- name: Configure
  include_tasks: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/_configure.yml"
  tags:
    - configure

- name: Wait for consul api
  wait_for:
    host: "127.0.0.1"
    port: "{{ hs_consul_api_port }}"
    timeout: 60
  when: (inventory_hostname in groups['hashistack_minions']) or (inventory_hostname in groups['hashistack_sre'])

- name: Configure consul on Minions
  include_tasks: >-
    {{ role_path }}/tasks/{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/_consul_minions.yml
  when:
    - (inventory_hostname in groups['hashistack_minions']) or (inventory_hostname in groups['hashistack_sre'])
    - (groups['hashistack_minions'] | intersect(groups['hashistack_sre']) | length) == 0
  tags:
    - consul_minions

- name: Flush before leaving
  meta: flush_handlers
  tags: always
