---
- name: Create local facts directory
  file:
    path: /etc/ansible/facts.d
    recurse: true
    state: directory

- name: Load os-specific vars
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars
  tags: always

- name: Execute os-specific tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_tasks_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  tags: always

- name: Flush
  meta: flush_handlers

- name: Wait for consul api
  wait_for:
    host: "127.0.0.1"
    port: "{{ hs_consul_api_port }}"
    timeout: 60
  when: __hs_consul_is_master

- name: "ACL Bootstrap"
  include_tasks:
    file: "_acl_bootstrap.yml"
    apply:
      tags: hs_consul_bootstrap
  when: __hs_consul_bootstrap_is_appliable

- name: "Add local fact: ansible_local.hs_consul.role_applied"
  copy:
    dest: "/etc/ansible/facts.d/hs_consul.fact"
    content: >-
      {{ {'role_applied': True} | to_json }}
    mode: 0600

- name: Configure consul instance using terraform
  include_tasks: _tf_configure.yml


- name: Execute os-specific _configure tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_configure_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  tags: configure

- name: Wait for consul api
  wait_for:
    host: "127.0.0.1"
    port: "{{ hs_consul_api_port }}"
    timeout: 60
  when: __hs_consul_is_minion

- name: Execute os-specific _consul_masters tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_configure_masters_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  when: __hs_consul_is_master
  tags:
    - hs_consul_masters

- name: Execute os-specific _consul_minions tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_configure_minions_precedence }}"
  loop_control:
    loop_var: _current_os_tasks
  when: __hs_consul_is_minion
  tags:
    - hs_consul_minions

- name: Flush before leaving
  meta: flush_handlers
  tags: always
