---
__hs_nomad_tls_ca_bundle: "/etc/ssl/certs/ca-certificates.crt"

__hs_nomad_hashicorp_apt_key: >-
  https://apt.releases.hashicorp.com/gpg
__hs_nomad_hashicorp_apt_repository: >-
  deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
