---
- name: Add hashicorp apt key.
  apt_key:
    url: "{{ __nomad_hashicorp_apt_key }}"
    state: present
    validate_certs: true

- name: Add hashicorp repo into sources list
  apt_repository:
    repo: "{{ __nomad_hashicorp_apt_repository }}"
    state: present

- name: Pin nomad release
  template:
    src: "apt.preferences.j2"
    dest: /etc/apt/preferences.d/nomad
    mode: 0640

- name: Install common packages
  apt:
    name: 
      - "nomad={{ nomad_version }}"
    state: present

- name: Get CNI plugins release
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /var/cache/cni-plugins-linux-amd64-v1.1.1.tgz
    mode: 0640

- name: Create CNI plugins directory
  file:
    path: "{{ __nomad_cni_plugins_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Extract CNI plugins"
  unarchive:
    src: /var/cache/cni-plugins-linux-amd64-v1.1.1.tgz
    remote_src: true
    dest: "{{ __nomad_cni_plugins_dir }}"
    owner: root
    group: root
    mode: 0755
    creates: "{{ __nomad_cni_plugins_dir }}/bridge"

- name: Create host volume directory
  file:
    path: "{{ _current_volume.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ nomad_volumes }}"
  loop_control:
    loop_var: _current_volume
