---
- name: Add hashicorp apt key.
  apt_key:
    url: "{{ __nomad_hashicorp_apt_key }}"
    state: present
    validate_certs: true
  tags:
    - online

- name: Add hashicorp repo into sources list
  apt_repository:
    repo: "{{ __nomad_hashicorp_apt_repository }}"
    state: present
  tags:
    - online

- name: Download common packages  # noqa: command-instead-of-module
  command: >
    apt-get install -y --download-only {{ packages_list | join(' ') }}
  tags:
    - online

- name: Download Network Docker image
  command: >
    skopeo copy docker://gcr.io/google_containers/pause-amd64:3.1 \ 
    docker-archive:/var/cache/pause-amd64-3-1.tar:gcr.io/google_containers/pause-amd64:3.1
  tags:
    - online

- name: Get CNI plugins release
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /var/cache/cni-plugins-linux-amd64-v1.1.1.tgz
    mode: 0640
  tags:
    - online
