---
- name: Create expected directories
  file:
    path: "{{ _current_expected_dir }}"
    owner: vault
    group: vault
    state: directory
    mode: 0700
  loop: "{{ __vault_expected_directories }}"
  loop_control:
    loop_var: _current_expected_dir

- name: Common private ssl directory
  file:
    path: "{{ __vault_tls_dir }}"
    owner: root
    group: "{{ __vault_ssl_cert_group }}"
    state: directory
    mode: 0750

- name: Add vault to ssl-cert group
  user:
    name: vault
    groups: "{{ __vault_ssl_cert_group }}"
    append: true

- name: Upload CA certificate
  copy:
    src: "{{ vault_local_ca_cert }}"
    dest: "{{ __vault_ca_certificate }}"
    owner: root
    group: "{{ __vault_ssl_cert_group }}"
    mode: 0644
  notify: Update ca trust
  when: vault_use_custom_ca

- name: Flush
  meta: flush_handlers

- name: Upload self certificate
  copy:
    src: "{{ _current_cert_part }}"
    dest: "{{ __vault_tls_dir }}/{{ _current_cert_part.split('/')[-1] }}"
    owner: root
    group: "{{ __vault_ssl_cert_group }}"
    mode: 0640
  loop:
    - "{{ vault_node_cert }}"
    - "{{ vault_node_cert_private_key }}"
    - "{{ vault_node_cert_fullchain }}"
  loop_control:
    loop_var: _current_cert_part
  notify: Restart vault

- name: Write vault server configuration
  template:
    src: "vault-server.hcl.j2"
    dest: "{{ __vault_conf_file }}"
    owner: vault
    group: vault
    mode: 0640
  notify: Restart vault
  when: __vault_is_master

- name: Flush
  meta: flush_handlers
