---
- name: Apply
  debug:
    msg: "Starting apply phase"
    verbosity: 1

- name: APPLY - Create a dedicated keypair
  community.crypto.openssh_keypair:
    path: "{{ hs_workspace_ssh_private_key_file }}"
    type: ed25519

- name: APPLY - Copy terraform sources    # noqa risky-file-permissions
  copy:
    src: "{{ tf_module_src }}"
    dest: "{{ tf_module_dest }}"

- name: Common
  include_tasks: _common.yml
  tags:
    - common

- name: APPLY - Terraform output extract
  set_fact:
    mono_ipv4: "{{ tf_result.outputs.mono_ipv4.value }}"
    mono_ipv6: "{{ tf_result.outputs.mono_ipv6.value }}"
    mono_private_ipv4: "{{ tf_result.outputs.mono_private_ipv4.value }}"
    current_ssh_user: "{{ tf_result.outputs.raw_ssh_user.value }}"
  when:
    - hs_archi == 'mono'
  tags:
    - outputs
    - molecule-notest

- name: APPLY - Terraform output extract
  set_fact:
    sre_ipv4: "{{ tf_result.outputs.sre_ipv4.value }}"
    sre_ipv6: "{{ tf_result.outputs.sre_ipv6.value }}"
    sre_private_ipv4: "{{ tf_result.outputs.sre_private_ipv4.value }}"
    current_ssh_user: "{{ tf_result.outputs.raw_ssh_user.value }}"
    masters_ipv4: "{{ tf_result.outputs.masters_ipv4.value }}"
    minions_ipv4: "{{ tf_result.outputs.minions_ipv4.value }}"
    private_network_id: "{{ tf_result.outputs.private_network_id.value }}"
  when:
    - hs_archi == 'multi'
  tags:
    - outputs
    - molecule-notest

- name: APPLY - Read ssh.cfg
  command: cat "{{ hs_workspace_root }}/ssh.cfg"
  register: _ssh_cfg_file
  changed_when: false

- name: APPLY - Add raw and ready host definitions to ssh config
  blockinfile:
    path: "{{ hs_workspace_root }}/ssh.cfg"
    state: present
    create: true
    mode: 0640
    marker: "{{ __tf_core_block_marker }}"
    block: |
      {{ lookup('template', hs_archi + '/_tf_core_ssh_cfg.j2') }}
  when: _ssh_cfg_file.stdout.find(__tf_core_block_marker_suffix) == -1
  tags:
    - outputs

- name: APPLY - Read inventory
  command: cat "{{ hs_workspace_root }}/inventory"
  register: _inventory_file
  changed_when: false
  tags:
    - molecule-notest

- name: APPLY - Add raw and ready host definitions to inventory group
  blockinfile:
    path: "{{ hs_workspace_root }}/inventory"
    state: present
    create: true
    mode: 0640
    marker: "{{ __tf_core_block_marker }}"
    block: |
      {{ lookup('template', hs_archi + '/_tf_core_inventory.j2') }}
  when: _inventory_file.stdout.find(__tf_core_block_marker_suffix) == -1
  tags:
    - outputs
    - molecule-notest

- name: APPLY - Render host vars
  template:
    src: "{{ hs_archi }}/_tf_core_vars.yml.j2"
    dest: "{{ hs_workspace_group_vars_dir }}/tf_{{ tf_module_name }}.yml"
    mode: 0640
  tags:
    - outputs

- name: APPLY - Render sre group vars
  template:
    src: "multi/_tf_core_sre_vars.yml.j2"
    dest: "{{ hs_workspace_sre_group_vars_dir }}/tf_{{ tf_module_name }}.sre.yml"
    mode: 0640
  when: hs_archi == 'multi'
  tags:
    - outputs

- name: APPLY - Render cluster group vars
  template:
    src: "multi/_tf_core_cluster_vars.yml.j2"
    dest: "{{ hs_workspace_group_vars_dir }}/tf_{{ tf_module_name }}.cluster.yml"
    mode: 0640
  when: hs_archi == 'multi'
  tags:
    - outputs
