---
- name: "Uninstall existing apt packages"
  apt:
    name: "getenvoy-envoy"
    state: absent

- name: "Prepare"
  include_tasks:
    file: "{{ role_path }}/tasks/common/_prepare.yml"
    apply:
      tags: prepare
  tags:
    - prepare
    - online


- name: "Install"
  include_tasks:
    file: "{{ role_path }}/tasks/common/_install.yml"
    apply:
      tags: install
  tags:
    - install

- name: "Configure"
  include_tasks:
    file: "{{ role_path }}/tasks/common/_configure.yml"
    apply:
      tags: configure
  tags:
    - configure

