---
#
# ```{include} ../../../roles/stage1_pip/README.md
# ```
#
# ## Role defaults
#
packages_list:
  - ansible-core
  - bcrypt
  - bpytop
  - cryptography
  - dnspython
  - passlib
  - duplicity

pip_root_folder_external: '/usr/lib/python3.11/EXTERNALLY-MANAGED'
