---
# * Protocol of the exposed API.
__hs_vault_api_protocol: "https"

__hs_vault_conf_api_addr: >-
  {{ __hs_vault_api_protocol }}://{{ hs_vault_api_address }}:{{ hs_vault_api_port }}
__hs_vault_api:
  status: "{{ __hs_vault_conf_api_addr }}/v1/sys/seal-status"
  init: "{{ __hs_vault_conf_api_addr }}/v1/sys/init"
  unseal: "{{ __hs_vault_conf_api_addr }}/v1/sys/unseal"
  dr_enable: "{{ __hs_vault_conf_api_addr }}/v1/sys/replication/dr/primary/enable"
  rekey: "{{ __hs_vault_conf_api_addr }}/v1/sys/rekey/init"
  rekey_update: "{{ __hs_vault_conf_api_addr }}/v1/sys/rekey/update"
  genroot: "{{ __hs_vault_conf_api_addr }}/v1/sys/generate-root/attempt"
  genroot_update: "{{ __hs_vault_conf_api_addr }}/v1/sys/generate-root/update"
  genroot_decode: "{{ __hs_vault_conf_api_addr }}/v1/sys/decode-token"
  leader: "{{ __hs_vault_conf_api_addr }}/v1/sys/leader"


__hs_vault_cluster_protocol: "https"
__hs_vault_conf_cluster_addr: >-
  {{ __hs_vault_cluster_protocol }}://{{ hs_vault_node_fqdn }}:{{ hs_vault_cluster_port }}


__hs_vault_ssl_cert_group: "ssl-cert"

__hs_vault_conf_dir: "/etc/vault.d"
__hs_vault_home_dir: "/opt/vault"

__hs_vault_snapshot_home_dir: "/opt/vault-snapshot"
__hs_vault_snapshot_dir: "{{ __hs_vault_snapshot_home_dir }}/snapshots"
__hs_vault_snapshot_duplicity_dir: "{{ __hs_vault_snapshot_home_dir }}/duplicity"

__hs_vault_data_dir: "{{ __hs_vault_home_dir }}/data"

__hs_vault_conf_file: "{{ __hs_vault_conf_dir }}/vault.hcl"

__hs_vault_tls_dir: "/etc/ssl/private"

__hs_vault_self_private_key: "{{ __hs_vault_tls_dir }}/{{ hs_vault_node_cert_private_key.split('/')[-1] }}"
__hs_vault_self_certificate: "{{ __hs_vault_tls_dir }}/{{ hs_vault_node_cert_fullchain.split('/')[-1] }}"

__hs_vault_ca_certificate: "{{ __hs_vault_certs_truststore_dir }}/vault.ca.crt"

__hs_vault_is_master: >-
  {{
    hs_vault_inventory_masters_group is defined
    and hs_vault_inventory_masters_group | length > 0
    and inventory_hostname in groups[hs_vault_inventory_masters_group]
  }}
__hs_vault_is_minion: "{{ not __hs_vault_is_master }}"

__hs_vault_first_master: >-
  {{ groups[hs_vault_inventory_masters_group][0] }}

__hs_vault_is_first_master: >-
  {{ inventory_hostname == __hs_vault_first_master }}

__hs_vault_master_partners: >-
  {{
    groups[hs_vault_inventory_masters_group]
    | difference([inventory_hostname])
    | map('regex_replace', '_', '-')
    | map('regex_replace', '$', '.' + hs_vault_domain)
  }}

__hs_vault_terraform_module: >-
  vault_config

__hs_vault_terraform_module_work_dir: >-
  {{ hs_vault_terraform_work_dir }}/{{ __hs_vault_terraform_module }}

__hs_vault_cluster_listener: "{{ hs_vault_listen_ipv4 }}:{{ hs_vault_cluster_port }}"
__hs_vault_api_listener: "{{ hs_vault_listen_ipv4 }}:{{ hs_vault_api_port }}"

__hs_vault_archive_url: >-
  https://releases.hashicorp.com/vault/{{ hs_vault_version }}/vault_{{ hs_vault_version }}_linux_amd64.zip
__hs_vault_archive_filename: "vault-{{ hs_vault_version }}.zip"
__hs_vault_local_archive_path: "{{ hs_vault_local_cache_dir }}/{{ __hs_vault_archive_filename }}"
__hs_vault_license_file: "{{ __hs_vault_conf_dir }}/vault.license"
