---
galaxy_info:
  role_name: "stage0"
  author: "Team"
  description: >-
    Hashistack Stage 0 - Infrastructure (coupled to collections playbooks)
  issue_tracker_url: >-
    https://github.com/wescale/hashistack/issues
  min_ansible_version: "2.14"
  license: MIT
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - iac

dependencies: []
