---
- name: Add hashicorp apt key.
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    validate_certs: true

- name: Add hashicorp repo into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main
    state: present

- name: Install common packages
  apt:
    name: "nomad={{ nomad_version }}"
    state: present

- name: Pin nomad release
  copy:
    dest: /etc/apt/preferences.d/nomad
    mode: 0640
    content: |
      Package: nomad
      Pin: version {{ nomad_version }}
      Pin-Priority: 1002

- name: Add nomad user to ssl-cert group
  user:
    name: nomad
    groups: ssl-cert
    append: true

- name: Check directories exist
  file:
    path: "{{ item }}"
    owner: nomad
    group: nomad
    state: directory
    mode: 0700
  loop: "{{ nomad_expected_directories }}"

- name: Common private ssl directory
  file:
    path: "{{ nomad_tls_dir }}"
    owner: root
    group: ssl-cert
    state: directory
    mode: 0750

- name: Get CNI plugins release
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz
    dest: /var/cache/cni-plugins-linux-amd64-v1.0.1.tgz

- name: Create CNI plugins directory
  file:
    path: /opt/cni/bin/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Extract CNI plugins"
  unarchive:
    src: /var/cache/cni-plugins-linux-amd64-v1.0.1.tgz
    remote_src: true
    dest: /opt/cni/bin/
    creates: /opt/cni/bin/bridge
