---
- name: Config Loki
  template:
    dest: "/etc/loki/config.yml"
    src: "{{ loki_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart loki

- name: Create Loki dir
  file:
    path: "/var/lib/loki"
    state: directory
    owner: loki
    group: loki
    mode: 0755