---
- name: Add grafana gpg key
  apt_key:
    url: https://packages.grafana.com/gpg.key 
    state: present
  tags:
    - prepare

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
  tags:
    - prepare

- name: Download common packages
  shell: >
      apt-get install -y --download-only {{ packages_list | join(' ') }}
  tags:
    - prepare
