---
galaxy_info:
  role_name: alloy
  namespace: hashistack
  author: "Team"
  description: >-
    Grafana Alloy OTLP collector
  issue_tracker_url: >-
    https://github.com/wescale/hashistack/issues
  min_ansible_version: "2.11"
  license: MIT
  standalone: false
  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - grafana
    - otlp
    - system

dependencies: []
