---
galaxy_info:
  role_name: "loki"
  author: "Team"
  description: >-
    Hashistack loki
  issue_tracker_url: >-
    https://github.com/wescale/hashistack/issues
  min_ansible_version: "2.14"
  license: MIT
  standalone: false
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - iac

dependencies: []


