---
- name: Prepare
  include_tasks: _prepare.yml
  tags:
    - prepare
    - grafana

- name: Install
  include_tasks: _install.yml
  tags:
    - install
    - grafana

- name: Configure
  include_tasks: _configure.yml
  tags:
    - configure
    - grafana
