#cloud-config
---
write_files:
  - content: |
      #!/usr/bin/env bash
      if [ "$IFACE" = "ens5" ]; then

        SELF_DEFAULT_IP=$(ip a show ens2 | grep -Po 'inet \K[\d.]+')
        SELF_DEFAULT_GW=$(python3 -c "import ipaddress; print(ipaddress.IPv4Network('$${SELF_DEFAULT_IP}/31', False)[0])")

        ip route replace default via $${SELF_DEFAULT_GW}
      fi
    owner: "root:root"
    permissions: "0755"
    path: "/etc/network/if-up.d/jump_host_reverse_route"

runcmd:
  - service networking restart
