---
- name: "[VAULT ENTREPRISE] Disaster recovery secondary cluster activation"
  hosts: "{{ hs_vault_inventory_primary_masters_group | default('hashistack_masters1[0]') }}"
  become: false
  gather_facts: true
  strategy: linear

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "__create_namespaces.yml"
        apply:
          tags:
            - vault
      tags:
        - vault

