---
- name: "[VAULT ENTREPRISE] Disaster recovery demote cluster "
  hosts: "{{ scope | default('hashistack_masters') }}"
  become: false
  gather_facts: true
  strategy: linear

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "__dr_cluster_demote.yml"
        apply:
          tags:
            - vault
      tags:
        - vault
