---
- name: "[VAULT ENTREPRISE] REVOKE TOKEN"
  hosts: "{{ scope | default(hs_vault_inventory_primary_masters_group) | default('hashistack_masters') }}"
  become: false
  gather_facts: false
  strategy: linear

  tasks:
    - name: "Revoke Current token"
      include_role:
        name: "vault"
        tasks_from: "__revoke_token.yml"
        apply:
          tags:
            - vault
      tags:
        - vault

