---
- name: "[VAULT ENTREPRISE] Auto snapshot cluster activation"
  hosts: "{{ hs_vault_inventory_primary_masters_group | default('hashistack_masters') }}"
  become: false
  gather_facts: true
  strategy: linear

  tasks:
    - name: "Vault"
      include_role:
        name: "vault"
        tasks_from: "__enable_autosnapshot.yml"
        apply:
          tags:
            - vault
      tags:
        - vault

